version: '3.8'
services:
  traffic-simulator:
    build: .
    image: hcmc-traffic-bot:latest
    container_name: traffic-bot-1
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./:/app
    command: python runner.py --scenario scenarios/area_all.json

  web-frontend:
    image: python:3.11-slim
    container_name: cityflow_frontend
    restart: unless-stopped
    ports:
      - "8080:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: python -m http.server 8000